
package JFrames;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Login extends javax.swing.JFrame {

    
    public Login() {
	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        homeCloseButton = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_userid = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        redirectForgetPassword = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        redirectRegister1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(300, 155));
        setUndecorated(true);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(1270, 790));
        jPanel2.setPreferredSize(new java.awt.Dimension(1270, 730));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homeCloseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/close.png"))); // NOI18N
        homeCloseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeCloseButtonMouseClicked(evt);
            }
        });
        jPanel2.add(homeCloseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1480, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/buffalo-leathers.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-860, 0, 1750, 860));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("User ID :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 390, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Password :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 450, -1, -1));

        txt_userid.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jPanel2.add(txt_userid, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 380, 275, 35));
        jPanel2.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 442, 275, 35));

        loginButton.setBackground(new java.awt.Color(0, 51, 255));
        loginButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("Login");
        loginButton.setBorder(null);
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        jPanel2.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 560, 382, 40));

        redirectForgetPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        redirectForgetPassword.setText("Forget Password ?");
        redirectForgetPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                redirectForgetPasswordMouseClicked(evt);
            }
        });
        jPanel2.add(redirectForgetPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 490, 130, 36));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Logos.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 130, -1, -1));

        redirectRegister1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        redirectRegister1.setText("Not a Memeber? Register Now!");
        redirectRegister1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                redirectRegister1MouseClicked(evt);
            }
        });
        jPanel2.add(redirectRegister1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 610, 220, 36));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1294, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1523, 828));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void redirectForgetPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_redirectForgetPasswordMouseClicked
        ResetPassword r = new ResetPassword();
	r.setVisible(true);
	this.dispose();
    }//GEN-LAST:event_redirectForgetPasswordMouseClicked

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
       
	if (txt_userid.getText().equals("")) {
	    JOptionPane.showMessageDialog(this, "Enter User ID");
	} else if (txt_password.getText().equals("")) {
	    JOptionPane.showMessageDialog(this, "Enter Password!");
	} else {
	    try {
		String un = txt_userid.getText();
		String pw = txt_password.getText();
		Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
	        Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=ExImp;selectMethod=cursor", "sa", "112233");
		Statement st = con.createStatement();
		String sql = "SELECT UserID, Password FROM [User] WHERE UserID = ?";
		PreparedStatement pst = con.prepareStatement(sql);
		pst.setString(1, un);
		ResultSet rs = pst.executeQuery();
		if (rs.next()) {
		    String uID = rs.getString("UserID");
		    String Pass = rs.getString("Password");
		    if (un.equals(uID) && pw.equals(Pass)) {
			if(un.equals("Admin")){
			HomeFrame ob = new HomeFrame();
			ob.setVisible(true);
			this.dispose();
			}
			else{
			HomeFrame ob = new HomeFrame("Admin");
			ob.setVisible(true);
			this.dispose();
			}
		    } else {
			JOptionPane.showMessageDialog(this, "Incorrect Data!");
		    }
		} else {
		    JOptionPane.showMessageDialog(this, "Server Error!");
		}

	    } catch (Exception e) {
		JOptionPane.showMessageDialog(this, "Couldn't Connect to Server!");
	    }
	}
    }//GEN-LAST:event_loginButtonActionPerformed

    private void homeCloseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeCloseButtonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_homeCloseButtonMouseClicked

    private void redirectRegister1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_redirectRegister1MouseClicked
        registerForm r = new registerForm();
	r.setVisible(true);
	this.dispose();
    }//GEN-LAST:event_redirectRegister1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new Login().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel homeCloseButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel redirectForgetPassword;
    private javax.swing.JLabel redirectRegister1;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_userid;
    // End of variables declaration//GEN-END:variables
}
