
package JFrames;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class ResetPassword extends javax.swing.JFrame {

    
    public ResetPassword() {
	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        homeCloseButton = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_answer = new javax.swing.JTextField();
        checkEmailBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ResetPassword = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        backButton = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        txt_securityQuestion = new javax.swing.JTextField();
        txt_confirmPassword = new javax.swing.JPasswordField();
        txt_password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(300, 155));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(1270, 790));
        jPanel2.setPreferredSize(new java.awt.Dimension(1270, 730));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homeCloseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/close.png"))); // NOI18N
        homeCloseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeCloseButtonMouseClicked(evt);
            }
        });
        jPanel2.add(homeCloseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1480, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Email");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 330, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Answer");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 460, -1, -1));

        txt_answer.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jPanel2.add(txt_answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 450, 450, 35));

        checkEmailBtn.setBackground(new java.awt.Color(0, 51, 255));
        checkEmailBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        checkEmailBtn.setForeground(new java.awt.Color(255, 255, 255));
        checkEmailBtn.setText("Check");
        checkEmailBtn.setBorder(null);
        checkEmailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkEmailBtnActionPerformed(evt);
            }
        });
        jPanel2.add(checkEmailBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 310, 130, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Logos.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Security Question");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 400, -1, -1));

        ResetPassword.setBackground(new java.awt.Color(0, 51, 255));
        ResetPassword.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ResetPassword.setForeground(new java.awt.Color(255, 255, 255));
        ResetPassword.setText("Reset Password");
        ResetPassword.setBorder(null);
        ResetPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResetPasswordMouseClicked(evt);
            }
        });
        ResetPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetPasswordActionPerformed(evt);
            }
        });
        jPanel2.add(ResetPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 640, 382, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("New Password");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 530, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("Confirm New Password");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 590, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ResetPass.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 720, 600));

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/BackIcon.png"))); // NOI18N
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });
        jPanel2.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        txt_email.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jPanel2.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 320, 275, 35));

        txt_securityQuestion.setEditable(false);
        txt_securityQuestion.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jPanel2.add(txt_securityQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 390, 450, 35));

        txt_confirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_confirmPasswordActionPerformed(evt);
            }
        });
        jPanel2.add(txt_confirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 580, 280, 35));
        jPanel2.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 520, 280, 35));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1523, 828));

        setSize(new java.awt.Dimension(1523, 828));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void checkEmailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkEmailBtnActionPerformed
       
	if(txt_email.getText().equals("") || !txt_email.getText().matches("^.+@.+\\..+$")){
	      JOptionPane.showMessageDialog(this, "Enter valid Email");
	}
	else{
	
	    try {
		Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
		Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=ExImp;selectMethod=cursor", "sa", "112233");

		String UserIDCheckz = txt_email.getText();
		String sql = "select Email, SecurityQuestion from [User] where Email = ?";
		PreparedStatement pst = con.prepareStatement(sql);
		pst.setString(1, UserIDCheckz);
		ResultSet rs = pst.executeQuery();
		if (rs.next()) {
		    String questionz = rs.getString("SecurityQuestion");
		    txt_securityQuestion.setText(questionz);
		    txt_answer.setText("");
		    txt_password.setText("");
		    txt_confirmPassword.setText("");
		} else {
		    JOptionPane.showMessageDialog(this, "User Email Not Found!");
		    txt_securityQuestion.setText("");
		    txt_answer.setText("");
		    txt_password.setText("");
		    txt_confirmPassword.setText(""); 
		}
	    }
	     catch (Exception e) {
		e.printStackTrace();
	    }
	}
    }//GEN-LAST:event_checkEmailBtnActionPerformed

    private void homeCloseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeCloseButtonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_homeCloseButtonMouseClicked

    private void ResetPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResetPasswordActionPerformed

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        Login ob = new Login();
        ob.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonMouseClicked

    private void ResetPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetPasswordMouseClicked
        
	if(txt_email.getText().equals("")){
	      JOptionPane.showMessageDialog(this, "Enter Email");
	}
	else if(txt_answer.getText().equals("")){
	      JOptionPane.showMessageDialog(this, "Enter answer");
	}
	else if(txt_password.getText().equals("")){
	      JOptionPane.showMessageDialog(this, "Enter Password");
	}
	else if(txt_confirmPassword.getText().equals("")){
	      JOptionPane.showMessageDialog(this, "Enter Confirm password");
	}
	else if(!txt_confirmPassword.getText().equals(txt_password.getText())){
	      JOptionPane.showMessageDialog(this, "Password Do not Match!");
	}
	else{
	
	    try {
		Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
		Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=ExImp;selectMethod=cursor", "sa", "112233");

		String UserIDCheckz = txt_email.getText();
		String AnswerZ = txt_answer.getText();
		String passz = txt_password.getText();
		String sql = "select Email, SecurityQuestion, Answer from [User] where Email = ?";
		PreparedStatement pst = con.prepareStatement(sql);
		pst.setString(1, UserIDCheckz);
		ResultSet rs = pst.executeQuery();
		if (rs.next()) {
		    String answerz = rs.getString("Answer");
		    
		    if(AnswerZ.equals(answerz)){
		       String sqlz = "Update [User] set Password = ? where Email = ?";
		       PreparedStatement pstz = con.prepareStatement(sqlz);
		       pstz.setString(1, passz);
		       pstz.setString(2, UserIDCheckz);

		       int rowCount = pstz.executeUpdate();

		       if (rowCount > 0) {
			   JOptionPane.showMessageDialog(this, "Password Updated Successfully!");
			   txt_email.setText("");
			   txt_securityQuestion.setText("");
			   txt_answer.setText("");
			   txt_password.setText("");
			   txt_confirmPassword.setText("");
			   
		       } else {
			   JOptionPane.showMessageDialog(this, "Couldn't Connect to Server!");
		       }
		    }
		    else{
			JOptionPane.showMessageDialog(this, "Your Answer is Incorrect!");
		    }

		} else {
		    JOptionPane.showMessageDialog(this, "User Email Not Found!");
		    txt_answer.setText("");
		    txt_password.setText("");
		    txt_confirmPassword.setText("");
		}
	    }

	     catch (Exception e) {
		e.printStackTrace();
	    }
	}
    }//GEN-LAST:event_ResetPasswordMouseClicked

    private void txt_confirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_confirmPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_confirmPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>
	//</editor-fold>
	//</editor-fold>
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new ResetPassword().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ResetPassword;
    private javax.swing.JLabel backButton;
    private javax.swing.JButton checkEmailBtn;
    private javax.swing.JLabel homeCloseButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt_answer;
    private javax.swing.JPasswordField txt_confirmPassword;
    private javax.swing.JTextField txt_email;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_securityQuestion;
    // End of variables declaration//GEN-END:variables
}
