/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airlinetuto;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author lenovo
 */
public class Cancellation extends javax.swing.JFrame {

    /**
     * Creates new form Cancellation
     */
    public Cancellation() {
        initComponents();
        GetTicket();
        flightcode.setEditable(false);
        DisplayCan();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TIdCb = new javax.swing.JComboBox<>();
        flightcode = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        CancellationTable = new javax.swing.JTable();
        BookBtn = new javax.swing.JButton();
        ResetBtn = new javax.swing.JButton();
        flightdate = new com.toedter.calendar.JDateChooser();
        back = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CloudWays");
        setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TIdCb.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        TIdCb.setForeground(new java.awt.Color(0, 0, 102));
        TIdCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TIdCbActionPerformed(evt);
            }
        });
        getContentPane().add(TIdCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 110, 30));

        flightcode.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        flightcode.setForeground(new java.awt.Color(0, 0, 102));
        getContentPane().add(flightcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, 140, 30));

        CancellationTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CancellationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        CancellationTable.setRowHeight(25);
        CancellationTable.setSelectionBackground(new java.awt.Color(102, 204, 255));
        jScrollPane1.setViewportView(CancellationTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 1000, 330));

        BookBtn.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        BookBtn.setForeground(new java.awt.Color(0, 0, 102));
        BookBtn.setText("Cancel");
        BookBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookBtnMouseClicked(evt);
            }
        });
        BookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookBtnActionPerformed(evt);
            }
        });
        getContentPane().add(BookBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 330, 100, 30));

        ResetBtn.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        ResetBtn.setForeground(new java.awt.Color(0, 0, 102));
        ResetBtn.setText("Reset");
        ResetBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResetBtnMouseClicked(evt);
            }
        });
        ResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ResetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, 90, 30));
        getContentPane().add(flightdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 260, 130, 30));

        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 690, 70, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\3.2\\lab\\isd\\project image\\cancel.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TIdCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TIdCbActionPerformed
        // TODO add your handling code here:
        GetFCode();
    }//GEN-LAST:event_TIdCbActionPerformed

    private void BookBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookBtnMouseClicked
        // TODO add your handling code here:

        if (flightcode.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Missing Information");
        } else {
            try {
                CountCanc();
                Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airlinedb", "root", "");
                PreparedStatement Add = Con.prepareStatement("insert into CancellationTbl values(?,?,?,current_timestamp())");
                Add.setInt(1, CId);
                Add.setInt(2, Integer.valueOf(TIdCb.getSelectedItem().toString()));
                Add.setString(3, flightcode.getText());
                //   Add.setString(4, flightdate.getDate().toString());

                int row = Add.executeUpdate();
                JOptionPane.showMessageDialog(this, "Ticket Cancelled");
                Con.close();
                Cancel();
                DisplayCan();
                GetTicket();
                //Clear();

            } catch (Exception e) {

                JOptionPane.showMessageDialog(this, e);

            }
        }
    }//GEN-LAST:event_BookBtnMouseClicked

    private void BookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BookBtnActionPerformed

    private void ResetBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetBtnMouseClicked
        // TODO add your handling code here:
        flightcode.setText("");
    }//GEN-LAST:event_ResetBtnMouseClicked

    private void ResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResetBtnActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        new MainForm().setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_backMouseClicked

    Connection Con = null;
    PreparedStatement pst = null;
    ResultSet Rs = null, Rs1 = null;
    Statement St = null, St1 = null;

    private void GetTicket() {

        try {

            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airlinedb", "root", "");
            St = Con.createStatement();
            String Query = "select * from BookingsTbl";
            Rs = St.executeQuery(Query);
            while (Rs.next()) {

                int T = Rs.getInt("TicketId");
                TIdCb.addItem(String.valueOf(T));

            }

        } catch (Exception e) {

        }

    }
    int tmp = 0;

    private void GetFCode() {
        if (tmp == 0) {
            tmp++;
            return;
        }
        String Query = "select * from BookingsTbl where TicketId=" + TIdCb.getSelectedItem().toString();
        Statement st;
        ResultSet rs;
        try {

            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airlinedb", "root", "");
            St = Con.createStatement();
            Rs = St.executeQuery(Query);
            if (Rs.next()) {

                flightcode.setText(Rs.getString("FICode"));

            }
        } catch (Exception e) {

        }
    }

    private void DisplayCan() {
        try {

            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airlinedb", "root", "");
            St = Con.createStatement();
            Rs = St.executeQuery("select * from CancellationTbl");
            CancellationTable.setModel(DbUtils.resultSetToTableModel(Rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    int CId = 0;

    private void CountCanc() {

        try {

            St1 = Con.createStatement();
            Rs1 = St1.executeQuery("select Max(CancId) from CancellationTbl");
            Rs1.next();
            CId = Rs1.getInt(1) + 1;

        } catch (Exception e) {

        }

    }

    private void Cancel() {

        try {
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airlinedb", "root", "");
            String Query = "Delete from BookingsTbl where TicketId = " + TIdCb.getSelectedItem();
            Statement Del = Con.createStatement();
            Del.executeUpdate(Query);
            // JOptionPane.showMessageDialog(this,"Flight Deleted");
            //DisplayFlight();
        } catch (Exception e) {

            JOptionPane.showMessageDialog(this, e);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cancellation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cancellation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cancellation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cancellation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cancellation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BookBtn;
    private javax.swing.JTable CancellationTable;
    private javax.swing.JButton ResetBtn;
    private javax.swing.JComboBox<String> TIdCb;
    private javax.swing.JLabel back;
    private javax.swing.JTextField flightcode;
    private com.toedter.calendar.JDateChooser flightdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
