/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airlinetuto;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author lenovo
 */
public class Flights extends javax.swing.JFrame {

    /**
     * Creates new form Flights
     */
    public Flights() {
        initComponents();
        DisplayFlight();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        flightcode = new javax.swing.JTextField();
        numberofseats = new javax.swing.JTextField();
        source = new javax.swing.JComboBox<>();
        destination = new javax.swing.JComboBox<>();
        save = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        flightstable = new javax.swing.JTable();
        back = new javax.swing.JLabel();
        takeofdate = new com.toedter.calendar.JDateChooser();
        search = new javax.swing.JComboBox<>();
        filter = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CloudWays");
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        flightcode.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        flightcode.setForeground(new java.awt.Color(0, 0, 102));
        flightcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightcodeActionPerformed(evt);
            }
        });
        getContentPane().add(flightcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 150, 30));

        numberofseats.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        numberofseats.setForeground(new java.awt.Color(0, 0, 102));
        getContentPane().add(numberofseats, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 510, 150, 30));

        source.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        source.setForeground(new java.awt.Color(0, 0, 102));
        source.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Italy", "Canada", "Singapore", "Australia", "America", "Dubai", "India", "Bangladesh" }));
        source.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sourceActionPerformed(evt);
            }
        });
        getContentPane().add(source, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 150, 30));

        destination.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        destination.setForeground(new java.awt.Color(0, 0, 102));
        destination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "London", "Italy", "Canada", "Singapore", "Australia", "America", "Dubai", "India", "Bangladesh" }));
        getContentPane().add(destination, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 150, 30));

        save.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        save.setForeground(new java.awt.Color(0, 0, 102));
        save.setText("Save");
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveMouseClicked(evt);
            }
        });
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        save.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                saveKeyPressed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 590, 80, 30));

        edit.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        edit.setForeground(new java.awt.Color(0, 0, 102));
        edit.setText("Edit");
        edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 590, 90, 30));

        delete.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        delete.setForeground(new java.awt.Color(0, 0, 102));
        delete.setText("Delete");
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 590, 90, 30));

        flightstable.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        flightstable.setForeground(new java.awt.Color(0, 0, 102));
        flightstable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        flightstable.setRowHeight(25);
        flightstable.setSelectionBackground(new java.awt.Color(102, 204, 255));
        flightstable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                flightstableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(flightstable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 700, 350));

        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 690, 70, 60));
        getContentPane().add(takeofdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 150, 30));

        search.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        search.setForeground(new java.awt.Color(0, 0, 102));
        search.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "London", "Italy", "Canada", "Singapore", "Australia", "America", "Dubai", "India", "Bangladesh" }));
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 210, 110, 40));

        filter.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        filter.setForeground(new java.awt.Color(0, 0, 102));
        filter.setText("Filter");
        filter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                filterMouseClicked(evt);
            }
        });
        filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterActionPerformed(evt);
            }
        });
        getContentPane().add(filter, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 210, 100, 40));

        refresh.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        refresh.setForeground(new java.awt.Color(0, 0, 102));
        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        getContentPane().add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 210, 100, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\3.2\\lab\\isd\\project image\\flights.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseClicked
        // TODO add your handling code here:

        if (flightcode.getText().isEmpty() || numberofseats.getText().isEmpty() || source.getSelectedIndex() == -1 || destination.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Missing Information");
        } else {
            try {

                Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airlinedb", "root", "");
                PreparedStatement Add = Con.prepareStatement("insert into FlightTbl values(?,?,?,?,?)");
                Add.setString(1, flightcode.getText());
                Add.setString(2, source.getSelectedItem().toString());
                Add.setString(3, destination.getSelectedItem().toString());
                Add.setString(4, takeofdate.getDate().toString());
                Add.setInt(5, Integer.valueOf(numberofseats.getText()));

                int row = Add.executeUpdate();
                JOptionPane.showMessageDialog(this, "Flight Added");
                Con.close();
                DisplayFlight();
                Clear();

            } catch (Exception e) {

                JOptionPane.showMessageDialog(this, e);

            }
        }
    }//GEN-LAST:event_saveMouseClicked

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveActionPerformed

    private void saveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_saveKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveKeyPressed

    private void Clear() {

        flightcode.setText("");
        numberofseats.setText("");

    }
    private void editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseClicked

        if (Key == "") {
            JOptionPane.showMessageDialog(this, "Select A Passenger");
        } else {
            try {
                //CountPassengers();
                Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airlinedb", "root", "");
                String Query = "Update FlightTbl set FISource=?,FIDest=?,FIDate=?,FISeats=? where FICode=?";
                PreparedStatement Add = Con.prepareStatement(Query);
                Add.setString(5, Key);
                Add.setString(1, source.getSelectedItem().toString());
                Add.setString(2, destination.getSelectedItem().toString());
                Add.setString(3, takeofdate.getDate().toString());
                Add.setString(4, numberofseats.getText());
                int row = Add.executeUpdate();
                JOptionPane.showMessageDialog(this, "Flight Updated");
                Con.close();
                DisplayFlight();
                Clear();

            } catch (Exception e) {

                JOptionPane.showMessageDialog(this, e);

            }
        }
    }//GEN-LAST:event_editMouseClicked

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editActionPerformed

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        // TODO add your handling code here:
        if (Key == "") {

            JOptionPane.showMessageDialog(this, "select a Flight");

        } else {
            try {
                Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airlinedb", "root", "");
                String Query = "Delete from FlightTbl where FICode = '" + Key + "'";
                Statement Del = Con.createStatement();
                Del.executeUpdate(Query);
                JOptionPane.showMessageDialog(this, "Flight Deleted");
                DisplayFlight();
            } catch (Exception e) {

                JOptionPane.showMessageDialog(this, e);
            }

        }
    }//GEN-LAST:event_deleteMouseClicked


    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteActionPerformed

    private void flightstableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flightstableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) flightstable.getModel();
        int MyIndex = flightstable.getSelectedRow();
        Key = model.getValueAt(MyIndex, 0).toString();
        source.setSelectedItem(model.getValueAt(MyIndex, 1).toString());
        destination.setSelectedItem(model.getValueAt(MyIndex, 2).toString());
        numberofseats.setText(model.getValueAt(MyIndex, 4).toString());

    }//GEN-LAST:event_flightstableMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        new MainForm().setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_backMouseClicked

    private void filterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filterMouseClicked
        /* try {
            String Search = (String) search.getSelectedItem();
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airlinedb", "root", "");
            St = Con.createStatement();
            Rs = St.executeQuery("select * from PassengersTbl");
            PassengersTable.setModel(DbUtils.resultSetToTableModel(Rs));
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e);
        }*/// TODO add your handling code here:
    }//GEN-LAST:event_filterMouseClicked

    private void filterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterActionPerformed
        try {
            String selectedNationality = (String) search.getSelectedItem();
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airlinedb", "root", "");
            String query = "SELECT * FROM flighttbl WHERE FIDest = ?";
            PreparedStatement pst = Con.prepareStatement(query);
            pst.setString(1, selectedNationality);
            ResultSet rs = pst.executeQuery();
            flightstable.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_filterActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed

        try {
            DefaultTableModel model = (DefaultTableModel) flightstable.getModel();
            model.setRowCount(0);  // Clear the table

            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airlinedb", "root", "");
            St = Con.createStatement();
            Rs = St.executeQuery("SELECT * FROM flighttbl");
            flightstable.setModel(DbUtils.resultSetToTableModel(Rs));
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_refreshActionPerformed

    private void flightcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flightcodeActionPerformed

    private void sourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sourceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sourceActionPerformed

    Connection Con = null;
    PreparedStatement pst = null;
    ResultSet Rs = null, Rs1 = null;
    Statement St = null, St1 = null;

    private void DisplayFlight() {
        try {

            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airlinedb", "root", "");
            St = Con.createStatement();
            Rs = St.executeQuery("select * from FlightTbl");
            flightstable.setModel(DbUtils.resultSetToTableModel(Rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    String Key = "";

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Flights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Flights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Flights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Flights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Flights().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JButton delete;
    private javax.swing.JComboBox<String> destination;
    private javax.swing.JButton edit;
    private javax.swing.JButton filter;
    private javax.swing.JTextField flightcode;
    private javax.swing.JTable flightstable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField numberofseats;
    private javax.swing.JButton refresh;
    private javax.swing.JButton save;
    private javax.swing.JComboBox<String> search;
    private javax.swing.JComboBox<String> source;
    private com.toedter.calendar.JDateChooser takeofdate;
    // End of variables declaration//GEN-END:variables
}
