/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airlinetuto;

/**
 *
 * @author lenovo
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JLabel();
        flights = new javax.swing.JLabel();
        passengers = new javax.swing.JLabel();
        tickets = new javax.swing.JLabel();
        cancellation = new javax.swing.JLabel();
        contactus = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CloudWays");
        setMinimumSize(new java.awt.Dimension(1300, 760));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 690, 70, 60));

        flights.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                flightsMouseClicked(evt);
            }
        });
        getContentPane().add(flights, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 260, 130));

        passengers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passengersMouseClicked(evt);
            }
        });
        getContentPane().add(passengers, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 220, 260, 120));

        tickets.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ticketsMouseClicked(evt);
            }
        });
        getContentPane().add(tickets, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 260, 140));

        cancellation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancellationMouseClicked(evt);
            }
        });
        getContentPane().add(cancellation, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, 250, 130));

        contactus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactusMouseClicked(evt);
            }
        });
        getContentPane().add(contactus, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 390, 250, 130));

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\3.2\\lab\\isd\\project image\\dashboard.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 760));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        new Splash().setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_backMouseClicked

    private void flightsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flightsMouseClicked
        new Flights().setVisible(true);
        this.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_flightsMouseClicked

    private void passengersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passengersMouseClicked
        new Passengers().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_passengersMouseClicked

    private void ticketsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ticketsMouseClicked
        new TicketBooking().setVisible(true);
        this.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_ticketsMouseClicked

    private void cancellationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancellationMouseClicked
        new Cancellation().setVisible(true);
        this.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_cancellationMouseClicked

    private void contactusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactusMouseClicked
        new EmergencyContacts().setVisible(true);
        this.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_contactusMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel cancellation;
    private javax.swing.JLabel contactus;
    private javax.swing.JLabel flights;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel passengers;
    private javax.swing.JLabel tickets;
    // End of variables declaration//GEN-END:variables
}
