/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airlinetuto;

import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author lenovo
 */
public class Passengers extends javax.swing.JFrame {

    /**
     * Creates new form Passengers
     */
    public Passengers() {
        initComponents();
        DisplayPassengers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        passportno = new javax.swing.JTextField();
        zipcode = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        passengername = new javax.swing.JTextField();
        nationality = new javax.swing.JComboBox<>();
        gender = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        PassengersTable = new javax.swing.JTable();
        save = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        back = new javax.swing.JLabel();
        city = new javax.swing.JTextField();
        country = new javax.swing.JTextField();
        search = new javax.swing.JComboBox<>();
        refresh = new javax.swing.JButton();
        filter = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CloudWays");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        passportno.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        passportno.setForeground(new java.awt.Color(0, 0, 102));
        getContentPane().add(passportno, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 150, 30));

        zipcode.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        zipcode.setForeground(new java.awt.Color(0, 0, 102));
        zipcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zipcodeActionPerformed(evt);
            }
        });
        getContentPane().add(zipcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 460, 150, 30));

        phone.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        phone.setForeground(new java.awt.Color(0, 0, 102));
        getContentPane().add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 560, 150, 30));

        passengername.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        passengername.setForeground(new java.awt.Color(0, 0, 102));
        getContentPane().add(passengername, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 310, 30));

        nationality.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        nationality.setForeground(new java.awt.Color(0, 0, 102));
        nationality.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bangladeshi", "Italian", "Canadian", "Europian", "Australian", "American", "Indian", " " }));
        nationality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nationalityActionPerformed(evt);
            }
        });
        getContentPane().add(nationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 150, 30));

        gender.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        gender.setForeground(new java.awt.Color(0, 0, 102));
        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", " ", " " }));
        getContentPane().add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 150, 30));

        PassengersTable.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        PassengersTable.setForeground(new java.awt.Color(0, 0, 102));
        PassengersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        PassengersTable.setRowHeight(25);
        PassengersTable.setSelectionBackground(new java.awt.Color(102, 204, 255));
        PassengersTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PassengersTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(PassengersTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 750, 390));

        save.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        save.setForeground(new java.awt.Color(0, 0, 102));
        save.setText("Save");
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveMouseClicked(evt);
            }
        });
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 630, 80, 30));

        edit.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        edit.setForeground(new java.awt.Color(0, 0, 102));
        edit.setText("Edit");
        edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 630, 80, 30));

        delete.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        delete.setForeground(new java.awt.Color(0, 0, 102));
        delete.setText("Delete");
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 630, 80, 30));

        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 690, 70, 60));

        city.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        city.setForeground(new java.awt.Color(0, 0, 102));
        getContentPane().add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 510, 150, 30));

        country.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        country.setForeground(new java.awt.Color(0, 0, 102));
        getContentPane().add(country, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, 150, 30));

        search.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        search.setForeground(new java.awt.Color(0, 0, 102));
        search.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bangladeshi", "Italian", "Canadian", "Europian", "Australian", "American", "Indian", " " }));
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 210, 120, 40));

        refresh.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        refresh.setForeground(new java.awt.Color(0, 0, 102));
        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        getContentPane().add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 210, 100, 40));

        filter.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        filter.setForeground(new java.awt.Color(0, 0, 102));
        filter.setText("Filter");
        filter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                filterMouseClicked(evt);
            }
        });
        filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterActionPerformed(evt);
            }
        });
        getContentPane().add(filter, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 210, 100, 40));

        bg.setIcon(new javax.swing.ImageIcon("E:\\3.2\\lab\\isd\\project image\\passenger.jpg")); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 760));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nationalityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nationalityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nationalityActionPerformed

    private void PassengersTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PassengersTableMouseClicked
        // TODO add your handling code here:

        DefaultTableModel model = (DefaultTableModel) PassengersTable.getModel();
        int MyIndex = PassengersTable.getSelectedRow();
        Key = Integer.valueOf(model.getValueAt(MyIndex, 0).toString());
        passengername.setText(model.getValueAt(MyIndex, 1).toString());
        nationality.setSelectedItem(model.getValueAt(MyIndex, 2).toString());
        gender.setSelectedItem(model.getValueAt(MyIndex, 3).toString());
        passportno.setText(model.getValueAt(MyIndex, 4).toString());
        zipcode.setText(model.getValueAt(MyIndex, 5).toString());
        phone.setText(model.getValueAt(MyIndex, 6).toString());

    }//GEN-LAST:event_PassengersTableMouseClicked

    private void saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseClicked

        if (passengername.getText().isEmpty() || passportno.getText().isEmpty() || country.getText().isEmpty() || zipcode.getText().isEmpty() || city.getText().isEmpty() || phone.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Missing Information");
        } else {
            try {
                CountPassengers();
                Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airlinedb", "root", "");
                PreparedStatement Add = Con.prepareStatement("insert into PassengersTbl values(?,?,?,?,?,?,?,?,?)");
                Add.setInt(1, PassId);
                Add.setString(2, passengername.getText());
                Add.setString(3, nationality.getSelectedItem().toString());
                Add.setString(4, gender.getSelectedItem().toString());
                Add.setString(5, passportno.getText());
                Add.setString(6, country.getText());
                Add.setString(7, zipcode.getText());
                Add.setString(8, city.getText());
                Add.setString(9, phone.getText());

                int row = Add.executeUpdate();
                JOptionPane.showMessageDialog(this, "Passenger Added");
                Con.close();
                DisplayPassengers();
                Clear();

            } catch (Exception e) {

                JOptionPane.showMessageDialog(this, e);

            }
        }

    }//GEN-LAST:event_saveMouseClicked

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveActionPerformed

    private void editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseClicked
        // TODO add your handling code here:
        if (Key == 0) {
            JOptionPane.showMessageDialog(this, "Select A Passenger");
        } else {
            try {
                //CountPassengers();
                Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airlinedb", "root", "");
                String Query = "Update PassengersTbl set PName=?, PNat=?, PGen=?, Ppass=? ,Country=?, ZipCode=?, City=?, Pphone=? where PId=?";
                PreparedStatement Add = Con.prepareStatement(Query);
                Add.setInt(9, Key);
                Add.setString(1, passengername.getText());
                Add.setString(2, nationality.getSelectedItem().toString());
                Add.setString(3, gender.getSelectedItem().toString());
                Add.setString(4, passportno.getText());
                Add.setString(5, country.getText());
                Add.setString(6, zipcode.getText());
                Add.setString(7, city.getText());
                Add.setString(8, phone.getText());

                int row = Add.executeUpdate();
                JOptionPane.showMessageDialog(this, "Passenger Updated");
                Con.close();
                DisplayPassengers();
                Clear();

            } catch (Exception e) {

                JOptionPane.showMessageDialog(this, e);

            }
        }

    }//GEN-LAST:event_editMouseClicked

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editActionPerformed

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        // TODO add your handling code here:
        if (Key == 0) {

            JOptionPane.showMessageDialog(this, "select a Passenger");

        } else {
            try {
                Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airlinedb", "root", "");
                String Query = "Delete from PassengersTbl where PId=" + Key;
                Statement Del = Con.createStatement();
                Del.executeUpdate(Query);
                JOptionPane.showMessageDialog(this, "Passenger Deleted");

            } catch (Exception e) {

                JOptionPane.showMessageDialog(this, e);
            }

        }

    }//GEN-LAST:event_deleteMouseClicked

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        new MainForm().setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_backMouseClicked

    private void zipcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zipcodeActionPerformed

    private void filterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterActionPerformed
        try {
            String selectedNationality = (String) search.getSelectedItem();
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airlinedb", "root", "");
            String query = "SELECT * FROM PassengersTbl WHERE PNat = ?";
            PreparedStatement pst = Con.prepareStatement(query);
            pst.setString(1, selectedNationality);
            ResultSet rs = pst.executeQuery();
            PassengersTable.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_filterActionPerformed

    private void filterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filterMouseClicked
        /* try {
            String Search = (String) search.getSelectedItem();
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airlinedb", "root", "");
            St = Con.createStatement();
            Rs = St.executeQuery("select * from PassengersTbl");
            PassengersTable.setModel(DbUtils.resultSetToTableModel(Rs));
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e);
        }*/// TODO add your handling code here:
    }//GEN-LAST:event_filterMouseClicked

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed

        try {
            DefaultTableModel model = (DefaultTableModel) PassengersTable.getModel();
            model.setRowCount(0);  // Clear the table

            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airlinedb", "root", "");
            St = Con.createStatement();
            Rs = St.executeQuery("SELECT * FROM PassengersTbl");
            PassengersTable.setModel(DbUtils.resultSetToTableModel(Rs));
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_refreshActionPerformed

    Connection Con = null;
    PreparedStatement pst = null;
    ResultSet Rs = null, Rs1 = null;
    Statement St = null, St1 = null;

    private void DisplayPassengers() {
        try {

            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airlinedb", "root", "");
            St = Con.createStatement();
            Rs = St.executeQuery("select * from PassengersTbl");
            PassengersTable.setModel(DbUtils.resultSetToTableModel(Rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    int PassId = 0;

    private void CountPassengers() {

        try {

            St1 = Con.createStatement();
            Rs1 = St1.executeQuery("select Max(PId) from PassengersTbl");
            Rs1.next();
            PassId = Rs1.getInt(1) + 1;

        } catch (Exception e) {

        }

    }

    private void Clear() {

        passengername.setText("");
        passportno.setText("");
        country.setText("");
        zipcode.setText("");
        city.setText("");
        phone.setText("");

    }
    int Key = 0;

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Passengers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Passengers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Passengers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Passengers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Passengers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable PassengersTable;
    private javax.swing.JLabel back;
    private javax.swing.JLabel bg;
    private javax.swing.JTextField city;
    private javax.swing.JTextField country;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JButton filter;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> nationality;
    private javax.swing.JTextField passengername;
    private javax.swing.JTextField passportno;
    private javax.swing.JTextField phone;
    private javax.swing.JButton refresh;
    private javax.swing.JButton save;
    private javax.swing.JComboBox<String> search;
    private javax.swing.JTextField zipcode;
    // End of variables declaration//GEN-END:variables

}
