/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airlinetuto;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author HP
 */
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    public Registration() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstname = new javax.swing.JTextField();
        answer = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        confirmpassword = new javax.swing.JPasswordField();
        createAccount = new javax.swing.JButton();
        signin = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        securityquestion = new javax.swing.JComboBox<>();
        lastname = new javax.swing.JTextField();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CloudWays");
        setMinimumSize(new java.awt.Dimension(1300, 760));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        firstname.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        firstname.setForeground(new java.awt.Color(0, 0, 102));
        firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameActionPerformed(evt);
            }
        });
        getContentPane().add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 270, 30));

        answer.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        answer.setForeground(new java.awt.Color(0, 0, 102));
        answer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerActionPerformed(evt);
            }
        });
        getContentPane().add(answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 510, 270, 30));

        phone.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        phone.setForeground(new java.awt.Color(0, 0, 102));
        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });
        getContentPane().add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 330, 250, 30));

        email.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        email.setForeground(new java.awt.Color(0, 0, 102));
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 390, 250, 30));

        confirmpassword.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        confirmpassword.setForeground(new java.awt.Color(0, 0, 102));
        getContentPane().add(confirmpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 510, 160, 30));

        createAccount.setBackground(new java.awt.Color(204, 204, 255));
        createAccount.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        createAccount.setForeground(new java.awt.Color(0, 0, 102));
        createAccount.setText("Create an Account");
        createAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createAccountMouseClicked(evt);
            }
        });
        createAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountActionPerformed(evt);
            }
        });
        getContentPane().add(createAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 600, 240, 30));

        signin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signinMouseClicked(evt);
            }
        });
        getContentPane().add(signin, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 640, 80, 30));

        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 680, 70, 60));

        password.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        password.setForeground(new java.awt.Color(0, 0, 102));
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 450, 250, 30));

        securityquestion.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        securityquestion.setForeground(new java.awt.Color(0, 0, 102));
        securityquestion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Question", "What is the name of your first pet?", "In which city were you born?", "What is your favorite color?", "Who was your childhood best friend?", " " }));
        getContentPane().add(securityquestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 442, 270, 40));

        lastname.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        lastname.setForeground(new java.awt.Color(0, 0, 102));
        lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameActionPerformed(evt);
            }
        });
        getContentPane().add(lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, 270, 30));

        bg.setIcon(new javax.swing.ImageIcon("E:\\3.2\\lab\\isd\\project image\\registration.jpg")); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 760));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed
    Connection Con = null;
    PreparedStatement pst = null;
    ResultSet Rs = null, Rs1 = null;
    Statement St = null, St1 = null;

    private void DisplayPassengers() {
        try {

            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airlinedb", "root", "");
            St = Con.createStatement();
            Rs = St.executeQuery("select * from registrationtbl");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }
    /*
    private void Clear() {

        firstname.setText("");
        answer.setText("");
        phone.setText("");
        email.setText("");
    }*/
    int Key = 0;
    private void firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameActionPerformed

    private void answerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answerActionPerformed

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        new Login().setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_backMouseClicked

    private void signinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signinMouseClicked
        new Login().setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_signinMouseClicked

    private void createAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountActionPerformed
        /*String firstName = Firstname.getText();
        String lastName = Lastname.getText();
        String phoneNumber = phone.getText();
        String userEmail = email.getText();
        char[] passwordChars = confirmpassword.getPassword();
        String userPassword = new String(passwordChars);
        boolean registrationSuccessful = performRegistration(firstName, lastName, phoneNumber, userEmail, userPassword);
         */

        String firstName = firstname.getText();
        String lastName = lastname.getText();
        String phoneNumber = phone.getText();
        String userEmail = email.getText();
        String Question = securityquestion.getSelectedItem().toString();
        String Answer = answer.getText();
        String Password = password.getText();
        String ConfirmPassword = confirmpassword.getText();

        if (firstname.getText().isEmpty() || lastname.getText().isEmpty() || phone.getText().isEmpty() || email.getText().isEmpty() || answer.getText().isEmpty() || password.getText().isEmpty() || confirmpassword.getText().isEmpty()) {

            JOptionPane.showMessageDialog(this, "Enter Details");

        } else if (!(userEmail.contains("@gmail.com") || userEmail.contains("@yahoo.com") || userEmail.contains("@hotmail.com"))) {
            JOptionPane.showMessageDialog(null, "Invalid Email Address");
        } else if (Password.length() < 8) {
            JOptionPane.showMessageDialog(this, "Password must contain minimum 8 characters!");
        } else {
            try {
                //Class.forName("com.mysql.cj.jdbc.Driver");
                Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airlinedb", "root", "");

                String sql = "insert into registrationtbl(FirstName,LastName,PhoneNo,Email,SecurityQuestion,Answer,Password) values(?,?,?,?,?,?,?)";
                PreparedStatement pst = Con.prepareStatement(sql);
                pst.setString(1, firstName);
                pst.setString(2, lastName);
                pst.setString(3, phoneNumber);
                pst.setString(4, userEmail);
                pst.setString(5, Question);
                pst.setString(6, Answer);
                pst.setString(7, Password);

                int rowCount = pst.executeUpdate();

                if (rowCount > 0) {
                    JOptionPane.showMessageDialog(this, "User Registration Completed!");
                    ClearF();
                    new Login().setVisible(true);
                    this.dispose();

                } else {
                    JOptionPane.showMessageDialog(this, "Couldn't Connect to Server!");
                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
//new MainForm().setVisible(true);
        //this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_createAccountActionPerformed

    public void ClearF() {
        firstname.setText("");
        lastname.setText("");
        password.setText("");
        confirmpassword.setText("");
        email.setText("");
        securityquestion.setSelectedItem("Select Question");
        answer.setText("");
        phone.setText("");

    }
    private void createAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createAccountMouseClicked
        new Login().setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_createAccountMouseClicked

    private void lastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answer;
    private javax.swing.JLabel back;
    private javax.swing.JLabel bg;
    private javax.swing.JPasswordField confirmpassword;
    private javax.swing.JButton createAccount;
    private javax.swing.JTextField email;
    private javax.swing.JTextField firstname;
    private javax.swing.JTextField lastname;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField phone;
    private javax.swing.JComboBox<String> securityquestion;
    private javax.swing.JLabel signin;
    // End of variables declaration//GEN-END:variables
/*
    private boolean performRegistration(String firstName, String lastName, String phoneNumber, String userEmail, String userPassword) {
        String url = "jdbc:mysql://localhost:3306/airlinedb";
        String username = "root";
        String dbPassword = "";

        try (Connection connection = DriverManager.getConnection(url, username, dbPassword)) {
            String insertQuery = "INSERT INTO registrationtbl (FirstName, LastName, PhoneNo, Email, Password) VALUES (?, ?, ?, ?, ?)";

            try (PreparedStatement preparedStatement = connection.prepareStatement(insertQuery)) {
                preparedStatement.setString(1, firstName);
                preparedStatement.setString(2, lastName);
                preparedStatement.setString(3, phoneNumber);
                preparedStatement.setString(4, userEmail);
                preparedStatement.setString(5, userPassword);

                int rowsAffected = preparedStatement.executeUpdate();

                return rowsAffected > 0;
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error: Registration failed. Please try again.");
            return false;
        }
    }*/

    //To change body of generated methods, choose Tools | Templates.
}
