/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airlinetuto;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class ResetPassword extends javax.swing.JFrame {

    /**
     * Creates new form ResetPassword
     */
    public ResetPassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        confirmpassword = new javax.swing.JPasswordField();
        newpassword = new javax.swing.JPasswordField();
        resetpassword = new javax.swing.JButton();
        check = new javax.swing.JButton();
        securityquestion = new javax.swing.JTextField();
        answer = new javax.swing.JTextField();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 760));
        setPreferredSize(new java.awt.Dimension(1300, 760));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 630, 90, 80));

        email.setBackground(new java.awt.Color(204, 204, 255));
        email.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        email.setForeground(new java.awt.Color(0, 0, 102));
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 230, 320, 30));

        confirmpassword.setBackground(new java.awt.Color(204, 204, 255));
        confirmpassword.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        confirmpassword.setForeground(new java.awt.Color(0, 0, 102));
        getContentPane().add(confirmpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 480, 320, 30));

        newpassword.setBackground(new java.awt.Color(204, 204, 255));
        newpassword.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        newpassword.setForeground(new java.awt.Color(0, 0, 102));
        getContentPane().add(newpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 420, 320, 30));

        resetpassword.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        resetpassword.setForeground(new java.awt.Color(0, 0, 102));
        resetpassword.setText("Reset Password");
        resetpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetpasswordMouseClicked(evt);
            }
        });
        resetpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(resetpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 550, 320, 40));

        check.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        check.setForeground(new java.awt.Color(0, 0, 102));
        check.setText("Check");
        check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkActionPerformed(evt);
            }
        });
        getContentPane().add(check, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 230, -1, 40));

        securityquestion.setBackground(new java.awt.Color(204, 204, 255));
        securityquestion.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        securityquestion.setForeground(new java.awt.Color(0, 0, 102));
        securityquestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                securityquestionActionPerformed(evt);
            }
        });
        getContentPane().add(securityquestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 300, 320, 30));

        answer.setBackground(new java.awt.Color(204, 204, 255));
        answer.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        answer.setForeground(new java.awt.Color(0, 0, 102));
        answer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerActionPerformed(evt);
            }
        });
        getContentPane().add(answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 360, 320, 30));

        bg.setIcon(new javax.swing.ImageIcon("E:\\3.2\\lab\\isd\\project image\\resetpass.jpg")); // NOI18N
        bg.setMaximumSize(new java.awt.Dimension(1300, 760));
        bg.setMinimumSize(new java.awt.Dimension(1300, 760));
        bg.setPreferredSize(new java.awt.Dimension(1300, 760));
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 760));

        getAccessibleContext().setAccessibleName("CloudWays");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        new Login().setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_backMouseClicked

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkActionPerformed
        if (email.getText().equals("") || !email.getText().matches("^.+@.+\\..+$")) {
            JOptionPane.showMessageDialog(this, "Enter valid Email");
        } else {

            try {
                //Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                Connection Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airlinedb", "root", "");

                String Useremail = email.getText();
                String sql = "select Email, SecurityQuestion from registrationtbl where Email = ?";
                PreparedStatement pst = Con.prepareStatement(sql);
                pst.setString(1, Useremail);
                ResultSet rs = pst.executeQuery();
                if (rs.next()) {
                    String question = rs.getString("SecurityQuestion");
                    securityquestion.setText(question);
                    answer.setText("");
                    newpassword.setText("");
                    confirmpassword.setText("");
                } else {
                    JOptionPane.showMessageDialog(this, "User Email Not Found!");
                    securityquestion.setText("");
                    answer.setText("");
                    newpassword.setText("");
                    confirmpassword.setText("");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_checkActionPerformed

    private void resetpasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetpasswordMouseClicked
        if (email.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Enter Email");
        } else if (answer.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Enter answer");
        } else if (newpassword.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Enter Password");
        } else if (confirmpassword.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Enter Confirm password");
        } else if (!confirmpassword.getText().equals(newpassword.getText())) {
            JOptionPane.showMessageDialog(this, "Password Do not Match!");
        } else {

            try {
                //Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                Connection Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airlinedb", "root", "");

                String Useremail = email.getText();
                String AnswerZ = answer.getText();
                String pass = newpassword.getText();
                String sql = "select Email, SecurityQuestion, Answer from registrationtbl where Email = ?";
                PreparedStatement pst = Con.prepareStatement(sql);
                pst.setString(1, Useremail);
                ResultSet rs = pst.executeQuery();
                if (rs.next()) {
                    String answerz = rs.getString("Answer");

                    if (AnswerZ.equals(answerz)) {
                        String sqlz = "Update registrationtbl set Password = ? where Email = ?";
                        PreparedStatement pstz = Con.prepareStatement(sqlz);
                        pstz.setString(1, pass);
                        pstz.setString(2, Useremail);

                        int rowCount = pstz.executeUpdate();

                        if (rowCount > 0) {
                            JOptionPane.showMessageDialog(this, "Password Updated Successfully!");
                            email.setText("");
                            securityquestion.setText("");
                            answer.setText("");
                            newpassword.setText("");
                            confirmpassword.setText("");

                        } else {
                            JOptionPane.showMessageDialog(this, "Couldn't Connect to Server!");
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Your Answer is Incorrect!");
                    }

                } else {
                    JOptionPane.showMessageDialog(this, "User Email Not Found!");
                    answer.setText("");
                    newpassword.setText("");
                    confirmpassword.setText("");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_resetpasswordMouseClicked

    private void securityquestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_securityquestionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_securityquestionActionPerformed

    private void answerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answerActionPerformed

    private void resetpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetpasswordActionPerformed
        new Login().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_resetpasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResetPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answer;
    private javax.swing.JLabel back;
    private javax.swing.JLabel bg;
    private javax.swing.JButton check;
    private javax.swing.JPasswordField confirmpassword;
    private javax.swing.JTextField email;
    private javax.swing.JPasswordField newpassword;
    private javax.swing.JButton resetpassword;
    private javax.swing.JTextField securityquestion;
    // End of variables declaration//GEN-END:variables
}
